/*
  # Complete All 12 Clothing Categories

  1. Extended Products
    - Tops (T-shirts, Tank tops, Button-ups, Blouses, Polos, Crop tops, Henleys)
    - Bottoms (Jeans, Dress pants, Leggings, Joggers, Shorts, Skirts, Cargo pants)
    - Outerwear (Hoodies, Jackets, Coats, Blazers, Windbreakers, Parkas, Vests)
    - Activewear (Sports bra, Gym shorts, Sweatpants, Compression, Running shirts, Track jackets, Cycling shorts)
    - Footwear (Sneakers, Boots, Sandals, Loafers, Heels, Dress shoes, Slides)
    - Underwear (Boxers, Briefs, Trunks, Panties, Long johns, Camisoles, Undershirts)
    - Swimwear (One-piece, Bikini, Swim trunks, Board shorts, Swim briefs, Rash guard, Tankini)
    - Formalwear (Suit, Tuxedo, Evening gown, Cocktail dress, Dress shirt, Dress trousers, Waistcoat)
    - Loungewear (Pajamas, Robes, Lounge pants, Oversized tees, Slippers, Nightgowns, Sweatshirts)
    - Accessories (Hats, Scarves, Gloves, Belts, Ties, Hair accessories, Sunglasses)
    - Workwear (Overalls, Coveralls, Work boots, Hi-vis vests, Tool belts, Cargo cover pants, Work jackets)
    - Seasonal (Raincoat, Snow pants, Thermal tops, Sun hats, Ponchos, Beach cover-ups, Waterproof boots)
*/

INSERT INTO products (
  name,
  category,
  subcategory,
  description,
  price,
  original_price,
  discounted_price,
  colors,
  sizes,
  image_url,
  featured,
  in_stock,
  sort_order
) VALUES

-- TOPS (7 items)
(
  'Eddjos Classic White Tank Top',
  'women',
  'Tank Top',
  'Breathable classic tank top perfect for layering or standalone wear in warm weather.',
  2499,
  NULL,
  NULL,
  ARRAY['White', 'Black', 'Cream', 'Navy'],
  ARRAY['XS', 'S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3369362/pexels-photo-3369362.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  12
),
(
  'Eddjos Slim Fit Button Shirt',
  'men',
  'Button-up Shirt',
  'Elegant slim-fit button-up shirt suitable for business or casual occasions.',
  6999,
  7999,
  6999,
  ARRAY['White', 'Light Blue', 'Pink', 'Beige'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/2037832/pexels-photo-2037832.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  13
),
(
  'Eddjos Women Blouse',
  'women',
  'Blouse',
  'Sophisticated women blouse with elegant draping and professional styling.',
  5999,
  NULL,
  NULL,
  ARRAY['White', 'Beige', 'Burgundy', 'Navy'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3831683/pexels-photo-3831683.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  14
),
(
  'Eddjos Casual Henley Shirt',
  'unisex',
  'Henley',
  'Comfortable henley shirt with classic ribbed collar perfect for casual wear.',
  3999,
  4999,
  3999,
  ARRAY['Black', 'White', 'Burgundy', 'Navy', 'Olive'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/3560044/pexels-photo-3560044.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  15
),
(
  'Eddjos Crop Top Trendy',
  'women',
  'Crop Top',
  'Fashionable crop top ideal for summer and casual outings.',
  2999,
  NULL,
  NULL,
  ARRAY['White', 'Black', 'Red', 'Yellow'],
  ARRAY['XS', 'S', 'M', 'L'],
  'https://images.pexels.com/photos/3622622/pexels-photo-3622622.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  16
),

-- BOTTOMS (7 items)
(
  'Eddjos Premium Denim Jeans',
  'unisex',
  'Jeans',
  'Classic denim jeans with perfect fit and durability for everyday wear.',
  7999,
  8999,
  7999,
  ARRAY['Blue', 'Black', 'Gray', 'Light Blue'],
  ARRAY['28', '30', '32', '34', '36', '38'],
  'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  17
),
(
  'Eddjos Formal Dress Pants',
  'men',
  'Dress Pants',
  'Refined dress pants perfect for business and formal settings.',
  8999,
  9999,
  8999,
  ARRAY['Black', 'Navy', 'Charcoal', 'Beige'],
  ARRAY['30', '32', '34', '36', '38'],
  'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  18
),
(
  'Eddjos Compression Leggings',
  'women',
  'Leggings',
  'High-waist compression leggings perfect for workouts and casual wear.',
  5499,
  6499,
  5499,
  ARRAY['Black', 'Navy', 'Gray', 'Maroon'],
  ARRAY['XS', 'S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3873427/pexels-photo-3873427.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  19
),
(
  'Eddjos Casual Joggers',
  'unisex',
  'Joggers',
  'Comfortable joggers for active lifestyle and casual relaxation.',
  5999,
  6999,
  5999,
  ARRAY['Black', 'Navy', 'Gray', 'Olive'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/3622622/pexels-photo-3622622.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  20
),
(
  'Eddjos Denim Shorts',
  'women',
  'Shorts',
  'Stylish denim shorts perfect for summer and casual occasions.',
  3999,
  4999,
  3999,
  ARRAY['Blue', 'Black', 'Light Blue', 'White'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  21
),
(
  'Eddjos Elegant Skirt',
  'women',
  'Skirt',
  'Elegant midi skirt suitable for various occasions and styles.',
  6999,
  7999,
  6999,
  ARRAY['Black', 'Navy', 'Burgundy', 'Tan'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3945688/pexels-photo-3945688.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  22
),

-- OUTERWEAR (7 items)
(
  'Eddjos Denim Jacket',
  'unisex',
  'Jacket',
  'Classic denim jacket perfect for all seasons and styles.',
  9999,
  10999,
  9999,
  ARRAY['Blue', 'Black', 'Light Blue'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  23
),
(
  'Eddjos Wool Coat',
  'women',
  'Coat',
  'Sophisticated wool coat for elegance and warmth during cold seasons.',
  19999,
  21999,
  19999,
  ARRAY['Navy', 'Black', 'Camel', 'Gray'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3622617/pexels-photo-3622617.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  24
),
(
  'Eddjos Casual Blazer',
  'men',
  'Blazer',
  'Sharp casual blazer for business-casual and formal occasions.',
  16999,
  18999,
  16999,
  ARRAY['Navy', 'Black', 'Charcoal', 'Brown'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3828215/pexels-photo-3828215.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  25
),
(
  'Eddjos Windbreaker Jacket',
  'unisex',
  'Windbreaker',
  'Lightweight windbreaker for outdoor activities and sports.',
  7499,
  8499,
  7499,
  ARRAY['Navy', 'Black', 'Red', 'Green'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  26
),
(
  'Eddjos Winter Parka',
  'unisex',
  'Parka',
  'Heavy-duty winter parka for extreme cold weather protection.',
  24999,
  27999,
  24999,
  ARRAY['Black', 'Navy', 'Gray', 'Olive'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/3407617/pexels-photo-3407617.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  27
),
(
  'Eddjos Sleeveless Vest',
  'unisex',
  'Vest',
  'Versatile sleeveless vest perfect for layering and styling.',
  4999,
  5999,
  4999,
  ARRAY['Black', 'Brown', 'Navy', 'Beige'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  28
),

-- ACTIVEWEAR (7 items)
(
  'Eddjos Sports Bra Pro',
  'women',
  'Sports Bra',
  'High-support sports bra designed for intense workouts and training.',
  5999,
  6999,
  5999,
  ARRAY['Black', 'Navy', 'Gray', 'Pink'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3873427/pexels-photo-3873427.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  29
),
(
  'Eddjos Gym Shorts',
  'unisex',
  'Gym Shorts',
  'Lightweight gym shorts with moisture-wicking technology.',
  3499,
  4499,
  3499,
  ARRAY['Black', 'Navy', 'Gray', 'Red'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  30
),
(
  'Eddjos Running Shirt',
  'unisex',
  'Running Shirt',
  'Breathable running shirt with performance fabric.',
  3999,
  4999,
  3999,
  ARRAY['Black', 'White', 'Blue', 'Green'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/3369362/pexels-photo-3369362.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  31
),
(
  'Eddjos Track Jacket',
  'unisex',
  'Track Jacket',
  'Sleek track jacket perfect for training and athletic activities.',
  7999,
  8999,
  7999,
  ARRAY['Black', 'Navy', 'Green', 'Red'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/3622622/pexels-photo-3622622.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  32
),
(
  'Eddjos Compression Leggings Pro',
  'women',
  'Compression Leggings',
  'Professional compression leggings for maximum support during workouts.',
  6999,
  7999,
  6999,
  ARRAY['Black', 'Navy', 'Purple', 'Teal'],
  ARRAY['XS', 'S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3873427/pexels-photo-3873427.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  33
),
(
  'Eddjos Cycling Shorts',
  'unisex',
  'Cycling Shorts',
  'Padded cycling shorts for comfortable long rides.',
  5999,
  6999,
  5999,
  ARRAY['Black', 'Navy', 'Gray'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  34
),

-- FOOTWEAR (7 items)
(
  'Eddjos Classic Sneakers',
  'unisex',
  'Sneakers',
  'Timeless classic sneakers perfect for everyday comfort and style.',
  7999,
  8999,
  7999,
  ARRAY['White', 'Black', 'Navy', 'Gray'],
  ARRAY['6', '7', '8', '9', '10', '11', '12', '13'],
  'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  35
),
(
  'Eddjos Leather Boots',
  'women',
  'Boots',
  'Stylish leather boots perfect for all seasons.',
  12999,
  14999,
  12999,
  ARRAY['Black', 'Brown', 'Tan', 'Burgundy'],
  ARRAY['5', '6', '7', '8', '9', '10', '11', '12'],
  'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  36
),
(
  'Eddjos Summer Sandals',
  'unisex',
  'Sandals',
  'Comfortable summer sandals perfect for beach and casual wear.',
  2999,
  3999,
  2999,
  ARRAY['Black', 'Brown', 'White', 'Tan'],
  ARRAY['5', '6', '7', '8', '9', '10', '11', '12', '13'],
  'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  37
),
(
  'Eddjos Formal Loafers',
  'men',
  'Loafers',
  'Sophisticated loafers for business and formal occasions.',
  8999,
  9999,
  8999,
  ARRAY['Black', 'Brown', 'Tan'],
  ARRAY['7', '8', '9', '10', '11', '12', '13'],
  'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  38
),
(
  'Eddjos Designer Heels',
  'women',
  'Heels',
  'Elegant designer heels perfect for special occasions.',
  10999,
  12999,
  10999,
  ARRAY['Black', 'Gold', 'Silver', 'Red'],
  ARRAY['5', '6', '7', '8', '9', '10', '11'],
  'https://images.pexels.com/photos/3622617/pexels-photo-3622617.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  39
),
(
  'Eddjos Casual Slides',
  'unisex',
  'Slides',
  'Comfortable casual slides perfect for quick outings.',
  2499,
  3499,
  2499,
  ARRAY['Black', 'White', 'Navy', 'Gray'],
  ARRAY['5', '6', '7', '8', '9', '10', '11', '12', '13'],
  'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  40
),

-- ACCESSORIES (7 items)
(
  'Eddjos Winter Beanie',
  'unisex',
  'Hats',
  'Cozy winter beanie to keep you warm and stylish.',
  2999,
  3999,
  2999,
  ARRAY['Black', 'Navy', 'Burgundy', 'Gray', 'Beige'],
  ARRAY['One Size'],
  'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  41
),
(
  'Eddjos Wool Scarf',
  'unisex',
  'Scarves',
  'Premium wool scarf for warmth and elegance.',
  3999,
  4999,
  3999,
  ARRAY['Navy', 'Black', 'Gray', 'Camel', 'Burgundy'],
  ARRAY['One Size'],
  'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  42
),
(
  'Eddjos Leather Belt',
  'unisex',
  'Belts',
  'Classic leather belt perfect for any outfit.',
  3499,
  4499,
  3499,
  ARRAY['Black', 'Brown', 'Tan'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  43
),
(
  'Eddjos Silk Tie',
  'men',
  'Ties',
  'Elegant silk tie perfect for formal occasions.',
  2999,
  3999,
  2999,
  ARRAY['Navy', 'Burgundy', 'Black', 'Gray', 'Red'],
  ARRAY['One Size'],
  'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  44
),
(
  'Eddjos Designer Sunglasses',
  'unisex',
  'Sunglasses',
  'Stylish sunglasses with UV protection.',
  5999,
  6999,
  5999,
  ARRAY['Black', 'Brown', 'Blue Lens', 'Gray Lens'],
  ARRAY['One Size'],
  'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  45
),

-- FORMALWEAR (7 items)
(
  'Eddjos Premium Suit',
  'men',
  'Suit',
  'Premium tailored suit perfect for business and formal events.',
  49999,
  54999,
  49999,
  ARRAY['Navy', 'Black', 'Charcoal', 'Gray'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3828215/pexels-photo-3828215.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  46
),
(
  'Eddjos Evening Gown',
  'women',
  'Evening Gown',
  'Elegant evening gown for special occasions and celebrations.',
  34999,
  39999,
  34999,
  ARRAY['Black', 'Navy', 'Burgundy', 'Gold'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/3622617/pexels-photo-3622617.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  47
),
(
  'Eddjos Cocktail Dress',
  'women',
  'Cocktail Dress',
  'Sophisticated cocktail dress for evening events.',
  16999,
  18999,
  16999,
  ARRAY['Black', 'Navy', 'Red', 'Burgundy'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  48
),
(
  'Eddjos Dress Shirt',
  'men',
  'Dress Shirt',
  'Premium dress shirt for formal occasions.',
  7999,
  8999,
  7999,
  ARRAY['White', 'Light Blue', 'Cream', 'Pink'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/2037832/pexels-photo-2037832.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  49
),

-- LOUNGEWEAR (7 items)
(
  'Eddjos Comfort Pajamas',
  'unisex',
  'Pajamas',
  'Ultra-soft pajamas for comfortable sleep and relaxation.',
  5999,
  6999,
  5999,
  ARRAY['Navy', 'Gray', 'White', 'Burgundy'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/3622622/pexels-photo-3622622.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  50
),
(
  'Eddjos Luxury Robe',
  'unisex',
  'Robes',
  'Luxurious robe perfect for comfort at home.',
  7999,
  8999,
  7999,
  ARRAY['Navy', 'Gray', 'Black', 'Cream'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/3622622/pexels-photo-3622622.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  51
),
(
  'Eddjos Lounge Pants',
  'unisex',
  'Lounge Pants',
  'Comfortable lounge pants for relaxation and casual wear.',
  4999,
  5999,
  4999,
  ARRAY['Black', 'Gray', 'Navy', 'Maroon'],
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'https://images.pexels.com/photos/3622622/pexels-photo-3622622.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  52
),
(
  'Eddjos Slippers',
  'unisex',
  'Slippers',
  'Cozy slippers for comfortable indoor wear.',
  2999,
  3999,
  2999,
  ARRAY['Black', 'Gray', 'Beige', 'Navy'],
  ARRAY['S', 'M', 'L', 'XL'],
  'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?w=800&h=800&fit=crop',
  false,
  true,
  53
);
